# Java 25 / WildFly 40 upgrade (25.104.x)
name: CPP Context Verify & Validation

trigger:
  branches:
    include:
      - main
      - 'team/*'
    exclude:
      - 'dev/release-*'
  paths:
    include:
    - '*'

pr:
  - '*'

resources:
  repositories:
    - repository: cppAzureDevOpsTemplates
      type: github
      name: hmcts/cpp-azure-devops-templates
      endpoint: 'hmcts'
      ref: 'wildfly40'

pool:
  name: "MDV-ADO-AGENT-AKS-01"
  demands:
    - identifier -equals ubuntu-j25-postgres

variables:
  sonarqubeProject: "uk.gov.moj.cpp.material:material-parent"
  service_Name: 'material'
  itTest_Folder: 'material-integration-test'

stages:
  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - template: pipelines/context-verify.yaml@cppAzureDevOpsTemplates
        parameters:
          sonarqube_project: ${{ variables['sonarqubeProject'] }}
          sonarQubeType: 'sonarQubeAKS'

  - ${{ if eq(variables['Build.Reason'], 'IndividualCI') }}:
      - template: pipelines/context-validation.yaml@cppAzureDevOpsTemplates
        parameters:
          repo: "$(Build.Repository.Name)"
          sonarQubeType: 'sonarQubeAKS'
          serviceName: ${{ variables['service_Name'] }}
          itTestFolder: ${{ variables['itTest_Folder'] }}
          aksDeployBranch: 'wildfly40'
