<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>uk.gov.moj.cpp.common</groupId>
        <artifactId>service-parent-pom</artifactId>
        <version>25.104.0-M10</version>
    </parent>

    <groupId>uk.gov.moj.cpp.material</groupId>
    <artifactId>material-parent</artifactId>
    <version>25.104.0-M1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>material-parent</name>
    <description>
        The material project serves as digital service/repository context for CPP platform.
    </description>

    <properties>
        <sonar.report.export.path>sonar-report.json</sonar.report.export.path>
        <sonar.scm.provider>git</sonar.scm.provider>
        <coredomain.version>25.104.0-M11</coredomain.version>
        <usersgroups.version>17.104.48</usersgroups.version>
        <stream-transformation-tool-anonymise.version>7.0.0</stream-transformation-tool-anonymise.version>
        <stream-transformation-tool.version>7.0.0</stream-transformation-tool.version>
        <mireportdata.cc.dependency.version>1.0.48</mireportdata.cc.dependency.version>
        <maven.failsafe.plugin.version>2.19.1</maven.failsafe.plugin.version>
        <jmeter.plugins.standard.version>1.3.1</jmeter.plugins.standard.version>
        <xml.maven.plugin.version>1.0.1</xml.maven.plugin.version>
        <rename.maven.plugin.version>1.0.1</rename.maven.plugin.version>
        <jmeter.lightning.maven.plugin.version>0.1.1</jmeter.lightning.maven.plugin.version>
        <junit4.version>4.13.1</junit4.version>
        <!--These azure lib versions override defined below are to be removed in
        PEG-377  as well as the corresponding entry in the dependencyManagement section -->
        <azure.functions.maven.plugin.version>1.24.0</azure.functions.maven.plugin.version>
        <material-azure.version>1.38.1</material-azure.version>
        <material-azure-storage.version>8.4.0</material-azure-storage.version>
        <jgitflow.maven.developBranchName>main</jgitflow.maven.developBranchName>
    </properties>

    <modules>
        <module>material-command</module>
        <module>material-domain</module>
        <module>material-event</module>
        <module>material-integration-test</module>
        <module>material-performance-test</module>
        <module>material-query</module>
        <module>material-viewstore</module>
        <module>material-service</module>
        <module>material-client</module>
        <module>material-event-sources</module>
        <module>material-datatypes-common</module>
        <module>material-azure-functions</module>
        <module>material-healthchecks</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>uk.gov.moj.cpp.core.domain</groupId>
                <artifactId>common-core-domain</artifactId>
                <version>${coredomain.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice</groupId>
                <artifactId>stream-transformation-tool-anonymise</artifactId>
                <version>${stream-transformation-tool-anonymise.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.justice</groupId>
                <artifactId>stream-transformation-tool-api</artifactId>
                <version>${stream-transformation-tool.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.gov.moj.cpp.core.domain</groupId>
                <artifactId>mireportdata-cc-dependency</artifactId>
                <version>${mireportdata.cc.dependency.version}</version>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit4.version}</version>
            </dependency>
            <dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure</artifactId>
                <version>${material-azure.version}</version>
            </dependency>
            <dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-storage</artifactId>
                <version>${material-azure-storage.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <archiveClasses>true</archiveClasses>
                    <attachClasses>true</attachClasses>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
